### ISSUE TITLE
Display records from map option broken

### ISSUE THREAD

**Issue by sacrevert** [BiologicalRecordsCentre/RISKy#13]
@johnvanbreda The display records from GBIF map using Ctrl and dragging appears to be broken

**Comment by johnvanbreda** [comment]
Fixed.
For info, it appears the GBIF API no longer accepts JSONP, so I switched to using the Indicia Proxy for calling the API.

**Comment by sacrevert** [comment]
Thanks John. Sounds like a useful thing to know!

**Comment by sacrevert** [comment]
This seems to have broken again @johnvanbreda

**Comment by johnvanbreda** [comment]
Looks like the site has been upgraded to Drupal 9 which caused this. @BirenRathod is risky.info now on Pantheon, if so, can you give me access please?

**Comment by BirenRathod** [comment]
@johnvanbreda yes it is on Pantheon. Also I haven't upgraded iform modules since migrated last year, so probably that could be one of the reason.
You have got now access to risky.info on Pantheon.

**Comment by johnvanbreda** [comment]
Thanks @BirenRathod 

@sacrevert I've fixed the things I found after a quick scan, but let me know if there are others as the site has been upgraded to a newer Drupal version.

**Comment by sacrevert** [comment]
@johnvanbreda brilliant, thanks John!

**Comment by sacrevert** [comment]
@johnvanbreda sorry, this still doesn't work for me (in Chrome). Hopefully this troubleshooting is useful for the new UKOTDAS website anyway!

**Comment by BirenRathod** [comment]
@sacrevert Can you try clearing cache and see if you get same result.

**Comment by sacrevert** [comment]
@BirenRathod yes, cleared all-time cache twice (yesterday and today), and still not working

**Comment by BirenRathod** [comment]
@sacrevert Which page is this? is it the one display on species details page?

**Comment by sacrevert** [comment]
Yes, e.g. see the map here. It is the 'Ctrl+drag box' option to get the GBIF record details that seems to be broken:
https://ris-ky.info/species/aeonium-arboreum

**Comment by BirenRathod** [comment]
Thanks @sacrevert. I have amended the path in javascript file which has resolved this problem.

**Comment by sacrevert** [comment]
Fantastic @BirenRathod Now seen working. Many thanks!
